# Generated by Django 6.0.7 on 2026-08-24 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the bank account being protected.', primary_key=True, serialize=False)),
                ('typical_login_hours', models.JSONField(blank=True, default=list, help_text='Hour ranges (0-23) during which this user normally logs in.')),
                ('typical_transfer_min', models.DecimalField(blank=True, decimal_places=2, help_text='Smallest transfer amount typically made by this user.', max_digits=14, null=True)),
                ('typical_transfer_max', models.DecimalField(blank=True, decimal_places=2, help_text='Largest transfer amount typically made by this user.', max_digits=14, null=True)),
                ('typical_recipients', models.JSONField(blank=True, default=list, help_text='List of beneficiary IDs this user has transferred to before.')),
                ('registered_devices', models.JSONField(blank=True, default=list, help_text='Device fingerprints previously seen on successful logins for this account.')),
                ('channel_preference', models.CharField(choices=[('app', 'Mobile app'), ('ussd', 'USSD'), ('both', 'Both app and USSD')], default='both', help_text='Channel(s) this customer normally banks through.', max_length=8)),
                ('account_age_days', models.PositiveIntegerField(default=0, help_text='Age of the bank account in days at time of scoring.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created.')),
            ],
            options={
                'verbose_name': 'bank user',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this session.', primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('app', 'Mobile app'), ('ussd', 'USSD')], help_text='Channel used for this session: mobile app or USSD.', max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the session started.')),
                ('device_fingerprint', models.CharField(blank=True, help_text='Hashed device fingerprint; NULL for USSD sessions on feature phones.', max_length=128, null=True)),
                ('sim_id', models.CharField(help_text='Salted hash of the SIM identity (IMSI); never stored raw.', max_length=64)),
                ('ip_or_cell_tower_id', models.CharField(help_text='Client IP address (app) or cell tower ID (USSD).', max_length=64)),
                ('location_geohash', models.CharField(help_text="Coarse (city-level) geohash of the session's location.", max_length=12)),
                ('session_duration_seconds', models.PositiveIntegerField(blank=True, help_text='Session length in seconds; NULL while still open.', null=True)),
                ('is_new_device', models.BooleanField(default=False, help_text="True if this session's device was never seen before.")),
                ('is_new_sim', models.BooleanField(default=False, help_text="True if this session's SIM was never seen before.")),
                ('user', models.ForeignKey(help_text='The bank account this session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.bankuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FraudLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attack', models.BooleanField(default=False, help_text='True if this session belongs to a simulated attack.')),
                ('attack_type', models.CharField(blank=True, choices=[('credential_theft', 'Credential theft'), ('sim_swap', 'SIM swap'), ('patient_low_and_slow', 'Patient low-and-slow drain')], help_text='Attack archetype for attack sessions; NULL otherwise.', max_length=32, null=True)),
                ('is_legitimate_anomaly', models.BooleanField(default=False, help_text='Suspicious-looking but genuinely legitimate activity (shared family device, genuine post-loss SIM replacement, etc.).')),
                ('session', models.OneToOneField(help_text='The session this ground-truth label applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='fraud_label', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='BehavioralFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_deviation_score', models.FloatField(default=0.0, help_text="Normalised deviation of login hour from user's baseline.")),
                ('amount_deviation_score', models.FloatField(blank=True, help_text='Normalised amount deviation; NULL if no transaction.', null=True)),
                ('device_change_flag', models.BooleanField(default=False, help_text='Session came from a device not seen before.')),
                ('sim_change_flag', models.BooleanField(default=False, help_text='Session used a SIM not seen before.')),
                ('location_change_flag', models.BooleanField(default=False, help_text='Session originated from a new coarse location.')),
                ('new_recipient_flag', models.BooleanField(default=False, help_text='Transfer targeted a brand-new beneficiary.')),
                ('velocity_count_5min', models.PositiveIntegerField(default=0, help_text='Transactions by this user in the last 5 minutes.')),
                ('combined_device_location_flag', models.BooleanField(default=False, help_text='True only when device-or-SIM change co-occurs with a location change; never True on either alone.')),
                ('menu_timing_deviation_score', models.FloatField(blank=True, help_text='USSD menu-navigation timing deviation; NULL on app sessions.', null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True, help_text='When this feature vector was computed.')),
                ('session', models.OneToOneField(help_text='The session these features were computed from.', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this transaction attempt.', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the transfer was attempted.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transfer amount in Naira.', max_digits=14)),
                ('recipient_id', models.CharField(help_text='Identifier of the transfer beneficiary.', max_length=64)),
                ('is_new_recipient', models.BooleanField(default=False, help_text='True if this beneficiary was never paid by this user before.')),
                ('time_since_last_transaction_seconds', models.PositiveIntegerField(blank=True, help_text="Seconds since the user's previous transaction; NULL for the first-ever transaction.", null=True)),
                ('session', models.ForeignKey(help_text='The session this transfer attempt occurred in.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.session')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', '-timestamp'], name='core_sessio_user_id_2e2219_idx'),
        ),
    ]
