# Generated by Django 6.0.7 on 2026-08-24 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the session started.'),
        ),
    ]
