# Generated by Django 6.0.7 on 2026-08-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_session_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudlabel',
            name='attack_type',
            field=models.CharField(blank=True, choices=[('credential_theft', 'Credential theft'), ('sim_swap', 'SIM swap'), ('patient_low_and_slow', 'Patient low-and-slow drain'), ('sim_swap_takeover', 'SIM swap takeover (USSD-native)')], help_text='Attack archetype for attack sessions; NULL otherwise.', max_length=32, null=True),
        ),
    ]
