# Generated by Django 6.0.7 on 2026-08-26 10:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fraudlabel_attack_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('500000.00'), help_text='Demo ledger balance; deducted ONLY on approved transfers.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bankuser',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='Customer display name for the demo bank app.', max_length=60),
        ),
        migrations.AddField(
            model_name='bankuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Demo signup handle. Uniqueness is enforced at the signup endpoint (a DB constraint is impossible here: the 250 seeded dataset customers predate this field and share the blank default).', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='outcome',
            field=models.CharField(choices=[('approve', 'Approved'), ('challenge', 'Challenged (verification)'), ('block', 'Blocked')], default='approve', help_text='Risk decision attached to this attempted transfer.', max_length=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Receipt / hold reference, e.g. SG-9F2C41AB.', max_length=24),
        ),
    ]
