# Generated by Django 6.0.7 on 2026-08-26 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bankuser_balance_bankuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralfeatures',
            name='keystroke_deviation_score',
            field=models.FloatField(blank=True, help_text='Keystroke rhythm deviation score (0.0-1.0); NULL for USSD or first few app sessions.', null=True),
        ),
        migrations.CreateModel(
            name='KeystrokeDynamics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avg_hold_time_ms', models.FloatField(help_text='Mean key hold duration in milliseconds.')),
                ('avg_interval_ms', models.FloatField(help_text='Mean inter-key interval in milliseconds.')),
                ('typing_speed_cpm', models.FloatField(help_text='Typing speed in characters per minute.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keystroke_dynamics', to='core.session')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['session'], name='core_keystr_session_572bf0_idx')],
            },
        ),
    ]
