# Generated by Django 6.0.7 on 2026-08-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_keystroke_dynamics'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='10-digit NUBAN account number.', max_length=10, unique=True)),
                ('display_name', models.CharField(help_text="Account holder's full name.", max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['account_number'],
            },
        ),
    ]
