# Generated by Django 6.0.7 on 2026-08-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_recipient_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='narration',
            field=models.CharField(blank=True, default='', help_text='Optional transfer description shown on receipts.', max_length=140),
        ),
    ]
