# Generated by Django 6.0.7 on 2026-08-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_transaction_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralfeatures',
            name='impossible_travel_flag',
            field=models.BooleanField(default=False, help_text='True when the implied speed from the immediately prior session to this one exceeds physically possible travel (>900 km/h) across a genuinely long distance.'),
        ),
        migrations.AddField(
            model_name='keystrokedynamics',
            name='login_pin_failures',
            field=models.PositiveIntegerField(blank=True, help_text='Number of incorrect login-PIN attempts before the successful login in this session (login-phase behavioural signal collected alongside the timing aggregate). NULL for dataset rows and for sessions that carried no login-phase data.', null=True),
        ),
    ]
