# Generated by Django 6.0.7 on 2026-08-29 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_behavioralfeatures_impossible_travel_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the transfer was attempted.'),
        ),
    ]
