# Generated by Django 6.0.7 on 2026-08-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='login_pin_hash',
            field=models.CharField(blank=True, help_text='PBKDF2 hash of the 6-digit login PIN. Never plaintext.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bankuser',
            name='transfer_pin_hash',
            field=models.CharField(blank=True, help_text='PBKDF2 hash of the 4-digit transfer PIN. Never plaintext.', max_length=128, null=True),
        ),
    ]
