# Generated by Django 6.0.7 on 2026-08-31 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bankuser_login_pin_hash_bankuser_transfer_pin_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_attack', models.BooleanField(default=False, help_text='True = reviewer confirmed this was a real fraud attempt; False = confirmed a genuine, legitimate session.')),
                ('source', models.CharField(choices=[('demo', 'Demo Control Room'), ('admin', 'Django admin')], default='demo', help_text='How / where the outcome was confirmed.', max_length=16)),
                ('confirmed_by', models.CharField(blank=True, default='', help_text='Free-text reviewer identifier (keep for the audit trail).', max_length=120)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(help_text='The scored session whose outcome a human has confirmed.', on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_outcome', to='core.session')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
