# Generated by Django 6.0.7 on 2026-09-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_confirmedoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystrokedynamics',
            name='backspace_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of corrections (Backspace/Delete) during the captured typing. Frequent corrections signal unfamiliarity with the number/amount being entered.', null=True),
        ),
        migrations.AddField(
            model_name='keystrokedynamics',
            name='hold_time_std_ms',
            field=models.FloatField(blank=True, help_text='Std-dev of key hold durations. Rhythm stability: a different typist on the same device tends to press keys with a noticeably different spread even when the mean looks plausible. NULL when the capture produced too few samples to estimate (or old rows).', null=True),
        ),
        migrations.AddField(
            model_name='keystrokedynamics',
            name='interval_std_ms',
            field=models.FloatField(blank=True, help_text='Std-dev of inter-key intervals. Burstiness: a machine/pecking rhythm vs a fluent one. NULL when too few samples to estimate.', null=True),
        ),
        migrations.AddField(
            model_name='keystrokedynamics',
            name='longest_pause_ms',
            field=models.FloatField(blank=True, help_text="Longest gap between consecutive keystrokes. Uncertainty pauses while hunting for keys are a strong 'not the routine typist' signal. NULL when too few samples to estimate.", null=True),
        ),
        migrations.AlterField(
            model_name='behavioralfeatures',
            name='velocity_count_5min',
            field=models.PositiveIntegerField(default=0, help_text='Transactions by this user in the last 2 minutes.'),
        ),
    ]
