# Generated by Django 6.0.7 on 2026-09-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_keystrokedynamics_backspace_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_count', models.PositiveIntegerField(default=0, help_text='Number of successful step-up verifications recorded for this account.')),
                ('verified_contexts', models.JSONField(blank=True, default=list, help_text='Rolling window of verified-context snapshots (capped in secondary_behavior.py to VERIFIED_HISTORY_LIMIT).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The account whose OTP-verified behaviour this profile encodes.', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_behavior_profile', to='core.bankuser')),
            ],
            options={
                'verbose_name': 'secondary behavior profile',
            },
        ),
        migrations.CreateModel(
            name='SecondaryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(help_text='The session whose OTP verification succeeded.', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_verification', to='core.session')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
    ]
